### ISSUE TITLE
EvtxECmd [feature request]: output file size limit

### ISSUE THREAD

**Issue by forensenellanebbia** [EricZimmerman/Issues#141]
I use EvtxECmd in combination with Timeline Explorer. Sometimes I'd love to have an option to make EvtxECmd split output into multiple CSV files when a certain output file size is reached. When reviewing massive amount of data, that would prevent the creation of very large CSV files.
![TLE](https://user-images.githubusercontent.com/8271353/88863472-3e4a1a00-d203-11ea-8bb9-900d287f04a7.png)

**Comment by EricZimmerman** [comment]
How big is big? Thats just a warning. i have seen people load 4GB csvs into TLE.

**Comment by forensenellanebbia** [comment]
Ehmm much bigger than that, 14GB in size

**Comment by EricZimmerman** [comment]
wow. i would say split up the logs into diff dirs then, until i can get around to possibly doing something like this.

that or script cutting up the file then adding the header row.

man that is a lot of event log data =)

**Comment by karch4n6** [comment]
Was just looking through Issues and found this request:  Would you consider something like a --split option for EvtxECmd?  Give the option of splitting the csv output up after x lines?  I know we can copy logs to separate folders / process in batches in order to have smaller output sets, but it might be nice to do all the splitting up front.

**Comment by EricZimmerman** [comment]
i would probably do it based on size vs # of lines

**Comment by EricZimmerman** [comment]
also note the latest TLE is loading 6GB+ csv files in ~8 mins

**Comment by EricZimmerman** [comment]
closing this for now. may revisit --split at some point
