### ISSUE TITLE
Timelineexplorer can't open .csv from plaso

### ISSUE THREAD

**Issue by MikeHofmann** [EricZimmerman/Issues#147]
Hi,

i'm evaluating plaso for our internal processing. Running on some testdata (malware samples taken from malpedia) and exporting it to l2tcsv i'm unable to open the file in Timelineexplorer. From the roughly 10k events, two seem to contain some characters which breaks Timelineexplorers parsing.

Steps to reproduce:

Timelineexplorer 1.2.0.0

open the attached .csv (added .txt extension to allow upload to giuthub):

[errors.csv.txt](https://github.com/EricZimmerman/Issues/files/5482619/errors.csv.txt)

regards,
Mike

PS: thx for the awesome work, we use it alot.

**Comment by EricZimmerman** [comment]
THe issue is bolded below.

date,time,timezone,MACB,source,sourcetype,type,user,host,short,desc,version,filename,inode,notes,format,extra
**00/00/0000,--:--:--**,UTC,....,LNK,Windows Shortcut,Not a time,-,-,[Empty description] Unknown                                     ...,[Empty description] File size: 0 File attribute flags: 0x00000000 cmd arguments: 

that is not a valid date, nor time.

you can script against the csv to remove garbage lines without too much trouble, or try to get them to not include those kinds of  things.

while i certainly could have TLE ignore such lines, its done as it is intentionally so you know when you have a data problem, vs just dropping lines with bad data

**Comment by MikeHofmann** [comment]
For older Versions of TLE this is true. But 1.2.0.0 seems to handle these dates just fine. Before that, i was removing these dates using `grep -v`.

But the issue was meant for line 3 (or 2 when not counting the header) with the timestamp `01/25/1970,09:28:16,UTC`.

**Comment by EricZimmerman** [comment]
ah perhaps i DID make that update then a version or so ago, to account for the bad data.

ill try to load that file in here when i get a moment and see if i can spot the issue, but it already looks strange, with a line feed in there, as well as the strange chars

**Comment by MikeHofmann** [comment]
I'm also wondering if this is also an issue in plaso. The source data (collection of a few thousand malware samples) looks uniform from filesystem metadata. Just two or three files seem to result in these strange chars. Could be the pe-parser from plaso which might be fooled by forged pe-headers.

When i find a moment i'll do further testing and might file an issue on the plaso project page as well. But i thought this would help TLE in recognizing malformed input and getting more resilient.

**Comment by EricZimmerman** [comment]
This is fixed.

the issue is that plaso is not supplying a value for the Description. I check that field for content to see how to color code things. since it was null that could not happen.

i added a check for null and return if the Desc is null, so the sample file loads fine now.

you can check for updates to get the fix and verify on your side.

as to why they are not supplying a Description, who knows

**Comment by MikeHofmann** [comment]
verified :+1: 

Thx alot
