### ISSUE TITLE
JumpList: Paths on (some?) mobile phones include garbage characters

### ISSUE THREAD

**Issue by kkriisgaard** [EricZimmerman/Issues#154]
I've encountered an odd problem with the JumpList parser: The locations of files/folders are shown to contain null characters, non-writable characters and other characters one wouldn't expect on a western system (particularly not on a Finnish phone). I've attached the jumplist containing the weird entries.

[f01b4d95cf55d32a.zip](https://github.com/EricZimmerman/Issues/files/5829982/f01b4d95cf55d32a.zip)

**Comment by AndrewRathbun** [comment]
![image](https://user-images.githubusercontent.com/36825567/104914799-a8937a00-595d-11eb-97dc-8dab3c571715.png)

Here's a screenshot, for convenience.

**Comment by EricZimmerman** [comment]
what does JLECmd do with these same paths, either to the screen or to csv?

**Comment by AndrewRathbun** [comment]
![image](https://user-images.githubusercontent.com/36825567/104930773-9b818580-5973-11eb-89ec-d9e345b27f98.png)

**Comment by AndrewRathbun** [comment]
CSV output here: [20210118095640_AutomaticDestinations.zip](https://github.com/EricZimmerman/Issues/files/5830947/20210118095640_AutomaticDestinations.zip)

**Comment by EricZimmerman** [comment]
looking at this closer now

**Comment by EricZimmerman** [comment]
so this is one of those "best effort" things in that these structures are not 100% understood. i can see the pattern to a degree in there, but without more test data showing this, its hard to say.

its a good thing we can see the partial string in there, as it gives us some indication of what is going on tho

i will look for more test data and improve parsing for these types of things once i can find more data.

here is an example, and how its different from other stuff i have seen. first red block is the length of decoded string, whose bytes are in blue (need 2x the number of bytes since utf8). Second red block is length of other string, which is 0x59x2 bytes, which ends at the bottom arrow. Strings are null terminated (which is what you are seeing in JLE stuff)



![image](https://user-images.githubusercontent.com/4265254/105074333-36529080-5a56-11eb-8509-af2dc9943882.png)
