### ISSUE TITLE
PECMD - Including the path of the referenced file in the Timeline output

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#163]
Would be a useful addition to the Prefetch Timeline output to include the source pf file, especially when combining active PF files with those carved from unallocated.

**Comment by EricZimmerman** [comment]
i have to be careful adding new columns because of the impact on things like 508, 500, etc but i may be able to add a new switch that when set, adds the path.

the idea of the timeline is not uberdettail tho, its a summary of exe's that ran, and when. if you see an interesting name, pivot into the main CSV.

CTRL-F in TLE helps with this as a double click filters the interesting hit quickly in each file

**Comment by randomaccess3** [comment]
Yeah it's less about uberdetail, more about it being useful for quickly generating the timeline. As you may miss the SourceCreated timestamp if the file has been executed one too many times, so then can manually pull that list out and when sorting know which timestamps relate to which.

Appreciate that 500/508 may cause some dramas for this.
