### ISSUE TITLE
RLA output change

### ISSUE THREAD

**Issue by timtaylor3** [EricZimmerman/Issues#190]
This maybe more of a clarification.  When using the the latest version of RLA with -d, the tool outputs a copy of the directory structure under specified updated directory instead of the cleaned registries.  Is this the new output scheme?  My concern is the possiblity of long paths causing an issue if this was intended.

**Comment by EricZimmerman** [comment]
it shouldnt unless you like to do an output path of

Some\folder\to\save\things\thru\that\should\be\alot\snaller

vs

C:\clean

i have it keep a copy of dir structure so that if you had a ton of hives to repair, it keeps things in line with where they came from. if we run into long file path issues i can revisit this tho

**Comment by timtaylor3** [comment]
Yeah, I wouldn't do that, but I know some that will.  Thanks. for the quick response.
