### ISSUE TITLE
XWFIM - contribute and update

### ISSUE THREAD

**Issue by Donovoi** [EricZimmerman/Issues#196]
Hi Eric, 

Just writing an issue to ask if there is way we can contribute to XWFIM? I would like to include downloading and copying excire, and if possible allowing it to create a portable install without the need for a local install.  I'm sure there is other stuff I'll think of aswell. 

All good if there is not a way for us to improve it, I'll then put in a more detailed issue as to what could be done.

Let me know what you think.

Regards,

**Comment by EricZimmerman** [comment]
i can probably add excire like i did other addons.

for the second, re: portable, i dont know how this would work. i have to have SOME place to stage files.

you could also just point XWFIM at a USB drive as its destination, but then you dont get the auto relative path thing (not hard to do manually once, but tradeoffs)

becoming a GitHub sponsor would be the best way to contribute since source code for XWFIM is not on Github. not that its secret sauce, just that youd need $1000 in third party controls to compile it

**Comment by Donovoi** [comment]
Ah I see. That makes sense thank you Eric! I'll sponsor if I'm not already. 

Not an important issue, just a nice to have.

**Comment by EricZimmerman** [comment]
this should all be in there
