### ISSUE TITLE
TLE: When CSV Has Missing Field from Header Column is Omitted Entirely 

### ISSUE THREAD

**Issue by reece394** [EricZimmerman/Issues#221]
When testing Block Parser I discovered a CSV it generated was missing a header field. When opening with Excel it displays all fields even though the header is missing. Attached is the file as an example [metadataedited.csv](https://github.com/user-attachments/files/16646645/metadataedited.csv). If possible I believe if TLE detects a difference it should handle this by displaying the column minus a name (maybe even generating a name like unknown column 1 etc..). Thanks again for the great tool!

Excel
![image](https://github.com/user-attachments/assets/05098864-ef35-4d7b-936c-49837930ab27)
TLE
![image](https://github.com/user-attachments/assets/a4496149-fabb-4087-885a-39bdd60c3299)

**Comment by EricZimmerman** [comment]
I would argue block parser should generate a valid CSV file =)

**Comment by reece394** [comment]
I agree it should and I did push a fix to it but I wanted to report this anyway in case other files had similar issues. Unfortunately we can’t control what data we are given on cases and it wouldn’t surprise me if I came across this issue again at some point 🤣

**Comment by EricZimmerman** [comment]
as the old saying goes, trust, but verify.

this is why its ideal to add direct support for these files via a plugin, so that you KNOW it was identified properly, and if a header field was missing, it would not show up as Block Parser, but as Generic CSV.

that is the preferred mechanism to find and become aware of these issues.
