### ISSUE TITLE
Do nuget packages for parsers

### ISSUE THREAD

**Issue by EricZimmerman** [EricZimmerman/Issues#24]

**Comment by Genbox** [comment]
Hi Eric,

I've published a nuget package for a fork here: https://github.com/Genbox/Registry
It is called Genbox.Registry to avoid confusion.

**Comment by EricZimmerman** [comment]
i ported stuff to netstandard2.0 and it auto generates a nuget package on build. i just have to push the ones i have here. thanks for doing this

**Comment by EricZimmerman** [comment]
also, i am ganking some of your changes and pulling them into the main repo.

you could have done push requests too for most of those. =)

**Comment by Genbox** [comment]
It was the plan to do some pull requests, but have barely had the time to sort through them lately. Most of the changes are related to the transaction log support as I wanted to extend the ways of taking in data as well as generalize the code to take in 0 to n logs instead of 1 to 2. It is not tested yet.

**Comment by EricZimmerman** [comment]
There won't ever be more than 2 tho. Hence my approach.

**Comment by Genbox** [comment]
Not even if previous transaction logs are restored from backup or carved from disk?

**Comment by EricZimmerman** [comment]
Maybe but they would have the same log1 and log2 names. And even then they
wouldn't have uncommitted transactions as far as I know.

**Comment by Genbox** [comment]
I see. Thanks for the clarification.
