### ISSUE TITLE
Timeline Explorer: Tab-separated file, values partially missing

### ISSUE THREAD

**Issue by inc0x0** [EricZimmerman/Issues#40]
I get some troubles opening tab-separated files in the Timeline Explorer (v 0.8.7.0). Columns are all correctly detected, however data is missing/wrong (value "0" instead of the actual value) in at least some rows of one column.

Expected result: Column "Expiry Time" should have 21 times "0" and 31 times some date/time value

Actual result: Column "Expiry Time" has 52 times "0" as value

This happened with several tab-separated files, however the attached one is the only I'm comfortable with uploading it.

Edit: renamed the file from .csv to .txt cause of github's limitations

[output2.txt](https://github.com/EricZimmerman/Issues/files/2460302/output2.txt)

**Comment by EricZimmerman** [comment]
from what i can see, its because there are 0s in a datetime column. while that makes sense to you seeing it as a human, or if its treated as a string (like in Excel), but TLE sees that columns data and determines its type, it treats it as numeric (a double to be precise). 

you can tell based on the filter that is in place. this is done when the data is imported, so i would look into getting whatever generated the csv file to either output an empty string, or something like 1970-01-01 00:00:00 or any valid date.
